// <auto-generated>
// This code was generated by LayerConstantsGenerator.
// </auto-generated>


namespace Constants
{
	public sealed class Layer
	{
		public const int Default = 0;
		public const int TransparentFX = 1;
		public const int IgnoreRaycast = 2;
		public const int Catchable = 3;
		public const int Water = 4;
		public const int UI = 5;
		
		public sealed class Mask
		{
			public const int Default = 1;
			public const int TransparentFX = 2;
			public const int IgnoreRaycast = 4;
			public const int Catchable = 8;
			public const int Water = 16;
			public const int UI = 32;
		}
	}
}