// <auto-generated>
// This code was generated by TagConstantsGenerator.
// </auto-generated>

using UnityEngine;

namespace Constants
{
	public sealed class Tag
	{
		public static readonly TagHandle Untagged = TagHandle.GetExistingTag("Untagged");
		public static readonly TagHandle Respawn = TagHandle.GetExistingTag("Respawn");
		public static readonly TagHandle Finish = TagHandle.GetExistingTag("Finish");
		public static readonly TagHandle EditorOnly = TagHandle.GetExistingTag("EditorOnly");
		public static readonly TagHandle MainCamera = TagHandle.GetExistingTag("MainCamera");
		public static readonly TagHandle Player = TagHandle.GetExistingTag("Player");
		public static readonly TagHandle GameController = TagHandle.GetExistingTag("GameController");
		public static readonly TagHandle Ground = TagHandle.GetExistingTag("Ground");
		public static readonly TagHandle Enemy = TagHandle.GetExistingTag("Enemy");
		public static readonly TagHandle Wall = TagHandle.GetExistingTag("Wall");
		public static readonly TagHandle Ball = TagHandle.GetExistingTag("Ball");
	}
}